-- Oracle schema for MOO SOR Alert Service
-- Run against FREEPDB1 as the 'moo' user

-- Drop existing tables (if re-seeding)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CHANNEL_PREFERENCES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER_SUBSCRIPTIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- Drop sequences
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SUB_SEQ';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE CHAN_SEQ';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

-- Customers table: one row per customer (mirrors MongoDB _id as PK)
CREATE TABLE CUSTOMERS (
    ID              VARCHAR2(24)    PRIMARY KEY,
    CUSTOMER_ID     VARCHAR2(20)    NOT NULL,
    FIRST_NAME      VARCHAR2(50),
    LAST_NAME       VARCHAR2(50)
);

-- Each alert subscription gets its own row (normalized from MongoDB embedded array)
CREATE TABLE CUSTOMER_SUBSCRIPTIONS (
    ID                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID         VARCHAR2(24)    NOT NULL REFERENCES CUSTOMERS(ID),
    SYMBOL              VARCHAR2(10)    NOT NULL,
    FACTSET_TRIGGER_ID  VARCHAR2(20)    NOT NULL,
    TRIGGER_TYPE_ID     VARCHAR2(5)     NOT NULL,
    TRIGGER_VALUE       VARCHAR2(10),
    ACTIVE_STATE        CHAR(1)         NOT NULL,
    SUBSCRIBED_AT       TIMESTAMP WITH TIME ZONE,
    DATE_DELIVERED      TIMESTAMP WITH TIME ZONE
);

-- Channel preferences: one row per notification channel per customer
CREATE TABLE CHANNEL_PREFERENCES (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID     VARCHAR2(24)    NOT NULL REFERENCES CUSTOMERS(ID),
    CHANNEL_TYPE    VARCHAR2(30)    NOT NULL,
    ENABLED         NUMBER(1)       NOT NULL,
    PRIORITY        NUMBER(3),
    ADDRESS         VARCHAR2(100),
    PHONE_NUMBER    VARCHAR2(20)
);

-- Indexes for query patterns used by the orchestration service
CREATE INDEX IDX_SUB_CUSTOMER_ID ON CUSTOMER_SUBSCRIPTIONS(CUSTOMER_ID);
CREATE INDEX IDX_SUB_TRIGGER_ID ON CUSTOMER_SUBSCRIPTIONS(FACTSET_TRIGGER_ID);
CREATE INDEX IDX_CHAN_CUSTOMER_ID ON CHANNEL_PREFERENCES(CUSTOMER_ID);

-- Sequences for batch loading (used by OracleTestDataGenerator)
CREATE SEQUENCE SUB_SEQ START WITH 1 INCREMENT BY 1 CACHE 10000;
CREATE SEQUENCE CHAN_SEQ START WITH 1 INCREMENT BY 1 CACHE 10000;
